// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrlnawlnuhgaqlkmgokj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFybG5hd2xudWhnYXFsa21nb2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDM0OTcsImV4cCI6MjA3MzI3OTQ5N30.sEKGAjGgvmLMEzhCJz_gfj2NExjTbhzy1quq6lnR1Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});